# Generated by Django 3.2.5 on 2021-08-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
